services:
  gitea:
    image: docker.gitea.com/gitea:latest

    container_name: gitea

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.home`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

    networks:
      - homelab

    ports:
      - "3000:3000"
      - "2222:22"

    volumes:
      - /srv/gitea:/data

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Kolkata

networks:
  homelab:
    external: true
